pipeline:
  name: reevzee-firstpipe
  identifier: reevzeefirstpipe
  projectIdentifier: REEVZEE_FIRST
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: reevzee
        repoName: go-app-cicd
        build: <+input>
  stages:
    - stage:
        name: build app
        identifier: build_app
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: reevzee_dock
                    repo: laceworklew/go-app-style
                    tags:
                      - fuzzy
    - stage:
        name: deploy app
        identifier: deploy_app
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: service_app
          environment:
            environmentRef: pre_prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: reevzeedel
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
